# Generated by Django 4.2.4 on 2023-08-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pix',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pix'),
        ),
    ]
