# Generated by Django 4.2.4 on 2023-08-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pix',
            field=models.ImageField(blank=True, default='images/profile_pix/default.jpg', null=True, upload_to='images/profile_pix'),
        ),
    ]
