# Generated by Django 4.2.4 on 2023-08-14 18:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=2000)),
                ('amount', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=1000)),
                ('visuals', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='house_images/'), size=None)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('radius', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('available', 'available'), ('rented-out', 'rented-out')], default='available', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
