# Generated by Django 4.2.4 on 2023-08-14 19:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='visuals',
        ),
        migrations.CreateModel(
            name='HouseVisuals',
            fields=[
                ('visual_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/house_images')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.house')),
            ],
        ),
    ]
