# Generated by Django 4.2.4 on 2023-08-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_house_address_alter_house_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housevisuals',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
