# Generated by Django 4.2.4 on 2023-08-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_housevisuals_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='bedroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('rent', 'rent'), ('lease', 'lease')], default='rent', max_length=7),
        ),
        migrations.AddField(
            model_name='house',
            name='furnished_type',
            field=models.CharField(choices=[('unfurnished', 'unfurnished'), ('semi-furnished', 'semi-furnished'), ('fully-furnished', 'fully-furnished')], default='unfurnished'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='tenant_type',
            field=models.CharField(choices=[('family', 'family'), ('bachelor', 'bachelor')], default='bachelor'),
        ),
    ]
